- .github/workflows/pr_title_validation.yml
---
- #79 
- PR Title 검증 Github Actions 로직입니다.
> [Chore] PR Title Validation

- .github/workflows/run_test_code.yml
---
- #79 
- 테스트가 성공해야 스테이징 브랜치에 머지할 수 있는 룰입니다.
> [Chore] Run Test Code When Merge

- src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
- src/main/java/org/hoongoin/interviewbank/exception/IbAccountNotMatchException.java
- src/main/java/org/hoongoin/interviewbank/exception/IbSoftDeleteException.java
- src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
- src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
---
- #86 
- 하다보니까 Account랑 Question도 soft delete에 대한 validation이 되어있지 않아서 적용했습니다.
- 테스트코드도 일단 기본적인부분만 해놨습니다.
> [Fix] Apply Soft Delete

- src/main/java/org/hoongoin/interviewbank/config/SpringfoxSwaggerBasePathResolver.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-staging.yml
---
- #88 
- Springfox 3.0.0 에서 해결안되는 에러를 Filter를 사용해 구현했습니다.
> [Fix] Springfox Swagger Server URL

- src/test/resources/application-test.yml
> [Fix] add swagger server url to application-test.yml

- src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapQuestionWithScrapAnswersResponse.java
- src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
---
- #94 
- 스크랩 서비스의 단위 테스트 코드 작성
> [Test] scrap service unit test

- src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
- src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
- src/test/java/org/hoongoin/interviewbank/authentication/InterviewApiAuthentication.java
- src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
- src/test/java/org/hoongoin/interviewbank/authentication/ScrapApiAuthentication.java
- src/test/java/org/hoongoin/interviewbank/config/IbWithMockUserSecurityContextFactory.java
- src/test/java/org/hoongoin/interviewbank/config/TestRedisConfig.java
---
- #96 
- 코드 다 짜기 전에 샘플로 만들어봤습니다.
---
- andExpect() 안에 400번대 에러가 날 때 테스트 명이 Fail인게 맞을까요?
- package를 지금처럼 따로 빼는게 나을까요? 아니면 도메인 하위에 authentication 패키지를 만드는게 나을까요? 아니면 도메인 하위의 컨트롤러 하위에 클래스로 만드는게 나을까요?
> [Test] API Authentication Test

- src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapAnswerController.java
- src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
---
- #100 
- @PostMapping 뒤 빈 괄호 삭제
- Controller 메소드 재정렬
- 포맷팅 적용
> [Refactor] Controller

- src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
---
- #100 
- 디테일한 에러 메세지가 프런트에 넘어가지 않도록 수정했습니다.
> [Refactor] error response message

- jenkins-trigger.sh
---
- #109 
- Jenkins에서 배포서버에 명령할 명령어 모음집
> [Feat] Add jenkins-trigger.sh file

- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
---
- #119 
- 쿼리에 By Interview인데 조건이 안걸려있었습니다!
- 테스트코드도 같이 추가해놨습니다.
> [Fix] Fix Question Query

- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
> [Fix] Fix FindInterview Logic Order By Asc to Desc

- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
> [Fix] oauth redirect uri

- build.gradle
- src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleJwtPayload.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenRequestParams.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenResponse.java
- src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
- src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
---
- #98 
- 프런트 연동해서 회원가입, 로그인 되는 것 까지 확인했습니다.
> [Fix] Google OAuth

- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
- src/main/resources/schema.sql
- src/test/resources/schema-test.sql
---
-  #98 
-  db schema password null 허용
- oauth login user id return
> [Fix] google oauth user

- src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
---
- #98 
- naver oauth redirect query를 optional로 변경
> [Fix] Naver OAuth Error Query Required False

- src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
> [Fix] naver oauth redirect error null

- src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
> [Fix] naver oauth converter

- db-backup/Dockerfile
- db-backup/backup.sh
- interview_bank_docker/docker-compose-local.yaml
- interview_bank_docker/docker-compose-staging.yaml
> [Feat] Implement db-backup

- src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
- src/main/java/org/hoongoin/interviewbank/common/discord/DiscordHandler.java
> [Fix] naver resttemplate converter

- src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenRequestParams.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenResponse.java
> [Fix] naver oauth

- src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
> [Fix] kakao oauth

- src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUerInfoResponse.java
- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
> [Fix] kakao response snake

- src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUerInfoResponse.java
> [Fix] kakao resonse id long

- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
> [Fix] kakao save entity

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
- src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
- src/test/java/org/hoongoin/interviewbank/account/controller/AccountControllerTest.java
> [Fix] account kakao and email password

- src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/application/dto/InterviewModifyDto.java
- src/main/java/org/hoongoin/interviewbank/interview/application/entity/Interview.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/request/CreateInterviewAndQuestionsRequest.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/request/UpdateInterviewRequest.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/response/CreateInterviewAndQuestionsResponse.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewPageResponse.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewResponse.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/response/UpdateInterviewResponse.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
- src/main/java/org/hoongoin/interviewbank/interview/enums/CareerYear.java
- src/main/java/org/hoongoin/interviewbank/interview/enums/InterviewPeriod.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntity.java
- src/main/resources/schema.sql
- src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
> [Feat] Implement interview attributes

- src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindMyInterviewResponse.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
- src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
> [Feat] my interview

- src/main/resources/application.yml
> [Fix] application.yaml staging

- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
---
- #117 
- &job-categories=1,2,3 으로 request요청시 sql in을 써서 multi select 가능하도록 구현했습니다.
- 스웨거에서는 list일 때 요청이 들어가지 않는 것으로 보입니다.
> [Fix] job category multi select

- src/main/java/org/hoongoin/interviewbank/account/AccountMapper.java
- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
- src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
- src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
- src/main/java/org/hoongoin/interviewbank/account/controller/response/GetMeResponse.java
- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
- src/main/java/org/hoongoin/interviewbank/account/infrastructure/entity/AccountEntity.java
- src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
- src/main/resources/schema.sql
- src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
- src/test/resources/schema-test.sql
> [Feat] Get My Account

- src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
- src/test/java/org/hoongoin/interviewbank/account/application/GoogleOAuthServiceTest.java
- src/test/resources/application-test.yml
> [Fix] google oauth uri

- src/main/java/org/hoongoin/interviewbank/InterviewbankApplication.java
- src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoOAuthProperties.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenResponse.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUserInfoResponse.java
- src/main/java/org/hoongoin/interviewbank/account/controller/KakaoOAuthController.java
- src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
- src/main/resources/application.yml
> [Refactor] kakao oauth

- src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
- src/main/java/org/hoongoin/interviewbank/account/controller/response/GetMeResponse.java
- src/main/java/org/hoongoin/interviewbank/account/controller/response/LoginResponse.java
> [Fix] Modify Profile Image API

- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-staging.yml
- src/main/resources/logback-spring.xml
> [Fix] Delete log filter and Modify timezone

- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
---
- #117 
- interview-period를 추가했습니다.
- Querydsl은 생각보다 복잡해서 수요일 이후에 다시 수정하겠습니다.
> [Fix] add interview period to interview search

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
- src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
- src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
- src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
---
- #52 
- 로그인 했을 때 (토큰 없이) 비밀번호를 변경할 수 있도록 api를 만들었습니다.
> [Feat] reset password when logged in

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
> [Fix] reset password

- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
- src/main/java/org/hoongoin/interviewbank/scrap/ScrapMapper.java
- src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
- src/main/java/org/hoongoin/interviewbank/scrap/application/entity/Scrap.java
- src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
- src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapResponse.java
- src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapResponse.java
- src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapCommandService.java
- src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapEntity.java
- src/main/resources/schema.sql
- src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
- src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
- src/test/resources/schema-test.sql
---
- #183
- database schema Scrap 테이블에 job category id 추가
- Interview, Scrap에서 job category not null로 변경
- Create Scrap, Read Detail Scrap시 생성 시간 Response에 추가
- Scrap Read All에서 Job Category 추가
> [Fix] scrap job category

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
- src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
- src/main/java/org/hoongoin/interviewbank/account/controller/response/InitializeProfileImageResponse.java
- src/main/resources/schema.sql
- src/test/resources/schema-test.sql
---
- #190 #189 
- 초기화 같은 경우는 private static final 로 상수처리 했습니다. 하드코딩이라 찝찝하긴하네여.. 환경변수로 빼기도 애매한게 POJO를 유지하고싶어서..
- profile image null시 오류가 자꾸나서 처리해줬습니다.
> [Fix] Add profile-image null And Implement initialize profile image

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
> [Fix] add register default image

- src/main/java/org/hoongoin/interviewbank/InterviewbankApplication.java
- src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
- src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
- src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverOAuthProperties.java
> [Refactor] oauth

- src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
> [Fix] naver oauth get profile response

- src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
> [Fix] modify saveProfileImage Default Image Delete

- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
- src/main/java/org/hoongoin/interviewbank/interview/enums/CareerYear.java
- src/main/java/org/hoongoin/interviewbank/interview/enums/InterviewPeriod.java
- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
---
- #117 
- search에 career year를 추가했습니다.
- career year enum과 interview period enum을 수정했습니다. (이부분은 피그마 한번 확인 부탁드립니다.)
> [Fix] interview search

- src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
- src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
> [Fix] interview update when question size is different from the original

- src/test/java/org/hoongoin/interviewbank/account/AccountTestFactory.java
- src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
- src/test/java/org/hoongoin/interviewbank/interview/InterviewTestFactory.java
- src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
- src/test/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntityTest.java
- src/test/java/org/hoongoin/interviewbank/scrap/ScrapMapperTest.java
- src/test/java/org/hoongoin/interviewbank/scrap/ScrapTestFactory.java
- src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
- src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
---
- #207 
- 테스트 팩토리 만들어서 대부분 수정했습니다.
- 테스트 팩토리에서 최대한 받아오게 해서 수정에 열려있도록 했지만, 어쩔수없이 매개변수 쓰는 부분은 있습니다. 매개변수 쓰면 수정할때 불편하긴한데 save가 꼭 필요한 부분이 있어서 이부분은 어쩔수 없네요
> [Refactor] Refactor Test Code

- Dockerfile
> [Fix] modify build timezone

- src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
---
- #211 
- 상위 카테고리 포함시 모두 검색되도록 수정
> [Fix] Modify Search Category 
